import { Canvas, useFrame } from "@react-three/fiber";
import { Grid, Sparkles, Stars } from "@react-three/drei";
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import { useRef } from "react";
import Shield3D from "../components/Shield3D";

function CameraDrift() { useFrame((state) => { const t = state.clock.elapsedTime; state.camera.position.x = Math.sin(t * .15) * .32; state.camera.position.y = .1 + Math.cos(t * .12) * .16; state.camera.lookAt(1.1, 0, 0); }); return null; }
function Rings() { const group = useRef(); useFrame((state) => { if (group.current) { group.current.rotation.z = state.clock.elapsedTime * .16; group.current.rotation.x = 1.05 + Math.sin(state.clock.elapsedTime * .22) * .08; } }); return <group ref={group} position={[2.15, .05, -.22]} rotation={[1.05, 0, .55]}>{[1.35, 1.78, 2.22].map((radius, i) => <mesh key={radius} rotation={[0, 0, i * .7]}><torusGeometry args={[radius, .01, 8, 100]} /><meshBasicMaterial color="#54e6df" transparent opacity={.38 - i * .07} /></mesh>)}</group>; }
function ScanPulse() { const ref = useRef(); useFrame((state) => { const progress = state.clock.elapsedTime % 2.2; const scale = .8 + progress * 1.25; if (ref.current) { ref.current.scale.setScalar(scale); ref.current.material.opacity = Math.max(0, .27 - progress * .12); } }); return <mesh ref={ref} position={[2.15, .05, -.38]} rotation={[1.05, 0, .55]}><ringGeometry args={[1.1, 1.13, 64]} /><meshBasicMaterial color="#72fff1" transparent /></mesh>; }
function Scene() { return <><color attach="background" args={["#07191f"]} /><fog attach="fog" args={["#07191f", 7, 19]} /><ambientLight intensity={.45} /><pointLight position={[2, 3, 3]} intensity={13} color="#63fff2" /><pointLight position={[-4, -1, 2]} intensity={5} color="#255cf3" /><pointLight position={[3, -2, 1]} intensity={4} color="#36d9cf" /><Stars radius={70} depth={30} count={2200} factor={3} saturation={0} fade speed={.25} /><Sparkles count={220} scale={[11, 7, 7]} size={1.5} speed={.22} color="#5af3e4" /><CameraDrift /><Shield3D /><Rings /><ScanPulse /><Grid position={[0, -2.95, -2]} args={[30, 30]} cellSize={.55} cellThickness={.4} cellColor="#117270" sectionSize={5} sectionThickness={.8} sectionColor="#35d6cd" fadeDistance={20} fadeStrength={1.4} infiniteGrid /><EffectComposer><Bloom intensity={2.15} luminanceThreshold={.08} luminanceSmoothing={.9} mipmapBlur /></EffectComposer></>; }
export default function HeroScene() { return <div className="hero-canvas" aria-hidden="true"><Canvas dpr={[1, 1.7]} camera={{ position: [0, .1, 7.4], fov: 42 }} gl={{ antialias: false }}><Scene /></Canvas></div>; }
