import { useEffect, useState, lazy, Suspense } from "react";
import { motion, useScroll } from "framer-motion";
import { FiActivity, FiArrowRight, FiCheck, FiChevronDown, FiCode, FiFileText, FiGithub, FiGlobe, FiLinkedin, FiMenu, FiPlay, FiShield, FiSliders, FiX } from "react-icons/fi";
const HeroScene = lazy(() => import("./scenes/HeroScene"));
const ScannerCard = lazy(() => import("./components/ScannerCard"));
import "./App.css";

const reveal = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .2 }, transition: { duration: .6 } };
const bento = [[FiShield,"Context-aware detection","Combines URL syntax, infrastructure, behavior, and brand signals into one defensible verdict."],[FiFileText,"Explainable verdicts","Give analysts the evidence behind every decision, not a black-box score."],[FiGlobe,"Threat intelligence","Enrich investigations with adversary infrastructure that evolves with the threat."],[FiActivity,"Real-time analysis","Return a clear risk decision before a user reaches a dangerous destination."],[FiSliders,"Enterprise reporting","Turn detections into audit-ready intelligence for leaders and responders."],[FiCode,"API access","Embed PhishLense protection into your workflows with an API built for scale."]];
const plans = [["Starter","For individual researchers","0","50 URL checks / month",["Live URL analysis","Core risk score","Community intelligence"]],["Professional","For growing security teams","149","10,000 URL checks / month",["Full threat reasoning","Intelligence enrichment","CSV evidence exports","Priority support"]],["Enterprise","For complex organizations","Custom","Designed around your environment",["Private cloud deployment","SSO and SOC integrations","Audit & compliance support","Dedicated success lead"]]];
const faqs = [["What signals does PhishLense analyze?","We combine URL structure, domain history, redirect behavior, certificates, brand impersonation patterns, and threat intelligence."],["Can we use PhishLense through an API?","Yes. The platform is API-first, so teams can connect it to mail gateways, SIEM workflows, browser protections, and internal tooling."],["How fast is the analysis?","Typical verdicts return in under 280 milliseconds, with richer investigation signals available alongside the initial decision."],["Is it suitable for enterprise environments?","Yes. Enterprise plans support private cloud options, audit-ready reporting, SSO, dedicated support, and SOC integrations."],["Does PhishLense store scanned URLs?","Customer controls determine data retention. Enterprise deployments can be configured around organizational privacy requirements."]];

function Counter({ value, label }) { const [shown, setShown] = useState("0"); useEffect(() => { let frame; const target = Number.parseInt(value, 10); let start; const tick = (time) => { if (!start) start = time; const progress = Math.min((time - start) / 1300, 1); setShown(String(Math.floor(target * progress))); if (progress < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [value]); return <article><strong>{shown}{value.replace(/[0-9]/g, "")}</strong><span>{label}</span></article>; }

function App() {
  const [openFaq, setOpenFaq] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const { scrollYProgress } = useScroll();
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 16); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <main className="site"><motion.div className="progress" style={{ scaleX: scrollYProgress }} />
    <section className="new-hero" id="home"><Suspense fallback={<div className="loading">Loading 3D Experience...</div>}>
  <HeroScene /></Suspense><nav className={`topbar wrap ${scrolled ? "compact" : ""}`}><a className="new-brand" href="#home"><i><FiShield /></i>PHISHLENSE</a><div className={`new-nav ${menuOpen ? "show" : ""}`}><a href="#platform">Platform</a><a href="#intelligence">Intelligence</a><a href="#enterprise">Enterprise</a><a href="#resources">Resources</a><a href="#pricing">Pricing</a></div><div className="top-actions"><button>Sign in</button><a className="mini-cta" href="#enterprise">Book demo</a><a className="top-cta" href="#analyze">Start protecting <FiArrowRight /></a></div><button className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <FiX /> : <FiMenu />}</button></nav>
      <div className="hero-wrap wrap"><motion.div {...reveal} className="hero-left"><span className="badge"><b /> AI SECURITY INTELLIGENCE</span><h1>See the threat<br /><em>before the click.</em></h1><p>Analyze suspicious URLs with AI-powered threat intelligence and explainable verdicts in milliseconds.</p><div className="hero-ctas"><a className="primary-btn" href="#analyze">Analyze a URL <FiArrowRight /></a><a className="secondary-btn" href="#demo"><FiPlay /> Watch demo</a></div><div className="hero-trust"><span><FiCheck /> No credit card</span><span><FiCheck /> API-first security</span><span><FiCheck /> Private by default</span></div></motion.div><motion.div {...reveal} transition={{ delay: .18 }} className="hero-console"><div className="console-head"><span><b /> LIVE THREAT VIEW</span><small>08:24:17 UTC</small></div><div className="console-score"><div className="console-gauge"><strong>87</strong><small>RISK SCORE</small></div><div><span className="danger-pill">LIKELY PHISHING</span><p>Account verification impersonation</p><small>Confidence 98.4%</small></div></div><div className="console-metrics"><span>DOMAIN AGE <b>2 days</b></span><span>REDIRECTS <b>3 hops</b></span><span>CERTIFICATE <b>Valid</b></span></div><div className="console-stream"><i /> DNS anomaly identified <time>NOW</time><i /> Credential capture pattern <time>NOW</time></div></motion.div></div>
      <div className="hero-metrics wrap"><span><b>99.8%</b> detection accuracy</span><span><b>280ms</b> average verdict</span><span><b>120+</b> signals analyzed</span><span><b>10M+</b> URLs inspected</span></div></section>

    <section className="scanner-band" id="analyze"><div className="wrap scanner-layout"><motion.div {...reveal}><span className="eyebrow-new">LIVE URL SCANNER</span><h2>One click from<br /><em>clarity.</em></h2><p>Investigate links at the speed of your inbox. PhishLense surfaces the signal, evidence, and recommended action in one focused workflow.</p><div className="signal-list"><span><FiCheck /> Private encrypted processing</span><span><FiCheck /> Evidence your SOC can act on</span></div></motion.div><motion.div {...reveal} transition={{ delay: .1 }}><Suspense fallback={<div className="loading">Loading Scanner...</div>}>
  <ScannerCard /></Suspense></motion.div></div></section>

    <section className="trust-strip"><div className="wrap"><p>TRUSTED BY 5,000+ SECURITY TEAMS WORLDWIDE</p><div className="trust-logos"><b>MICROSOFT</b><b>Google</b><b>Cisco</b><b>Cloudflare</b><b>PALO ALTO</b><b>AWS</b></div><div className="compliance"><span><FiCheck /> SOC 2 READY</span><span><FiCheck /> ISO 27001 ALIGNED</span><span><FiCheck /> GDPR SUPPORT</span><span><FiCheck /> 99.97% UPTIME</span></div></div></section>

    <section className="bento-section" id="platform"><div className="wrap"><motion.div {...reveal} className="section-heading"><span className="eyebrow-new">THE DEFENSE LAYER</span><h2>Intelligence that makes<br /><em>the next move obvious.</em></h2><p>Move from raw signals to clear decisions without slowing down your security operation.</p></motion.div><div className="bento-grid">{bento.map(([Icon,title,text], i) => <motion.article {...reveal} transition={{ delay: i * .05 }} whileHover={{ y: -7 }} className={`bento-card bento-${i}`} key={title}><Icon /><div className="graphic"><i /><i /><i /></div><h3>{title}</h3><p>{text}</p><a href="#intelligence">Explore capability <FiArrowRight /></a></motion.article>)}</div></div></section>

    <section className="product-demo" id="demo"><div className="wrap demo-grid"><motion.div {...reveal}><span className="eyebrow-new">ANALYST WORKSPACE</span><h2>Investigate with<br /><em>confidence.</em></h2><p>Every verdict is paired with a transparent investigation trail, so your team can explain the why, not just share the score.</p><ul><li><FiCheck /> Evidence organized by risk signal</li><li><FiCheck /> AI-generated investigation summary</li><li><FiCheck /> Exportable analyst-ready reports</li></ul><a className="text-button" href="#analyze">Open live scanner <FiArrowRight /></a></motion.div><motion.div {...reveal} className="dash-preview"><header><span><b /> ANALYSIS / 9C82F</span><small>SHARE REPORT</small></header><div className="dash-columns"><div><label>COMPOSITE RISK</label><strong>87<span>/100</span></strong><em>LIKELY PHISHING</em><div className="dash-chart">{[25,42,33,72,48,87,66,92,74,86].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div></div><div className="evidence"><label>KEY EVIDENCE</label><p><b>HIGH</b> Newly registered domain</p><p><b>HIGH</b> Credential collection form</p><p><b>MED</b> Brand lookalike string</p><label>AI ASSESSMENT</label><small>Signals align with a credential-harvesting campaign targeting financial services.</small></div></div></motion.div></div></section>

    <section className="how-section" id="intelligence"><div className="wrap"><motion.div {...reveal} className="section-heading centered"><span className="eyebrow-new">HOW PHISHLENSE WORKS</span><h2>Four steps to<br /><em>a safer decision.</em></h2></motion.div><div className="steps">{[["01","Submit URL","Send a suspicious destination through the scanner or API."],["02","Analyze Signals","Inspect infrastructure, behavior, and deception patterns."],["03","Generate Intelligence","Enrich the signals with current threat context."],["04","Deliver Verdict","Get an explainable risk decision your team can act on."]].map(([n,t,d])=><motion.article {...reveal} key={n}><b>{n}</b><span /><h3>{t}</h3><p>{d}</p></motion.article>)}</div></div></section>

    <section className="enterprise-new" id="enterprise"><div className="wrap enterprise-grid"><motion.div {...reveal}><span className="eyebrow-new">ENTERPRISE SECURITY</span><h2>Security your team<br />can <em>stand behind.</em></h2></motion.div><motion.div {...reveal}><p>Deploy phishing defense with the controls, integrations, and accountability an enterprise environment demands.</p><div className="enterprise-checks"><span><FiCheck /> Private cloud ready</span><span><FiCheck /> Audit-ready reporting</span><span><FiCheck /> SSO and API access</span><span><FiCheck /> SOC integrations</span><span><FiCheck /> Compliance support</span><span><FiCheck /> Dedicated security support</span></div><a className="primary-btn light" href="mailto:security@phishlense.ai">Talk to an expert <FiArrowRight /></a></motion.div></div></section>

    <section className="impact-section"><div className="wrap"><motion.div {...reveal} className="section-heading centered"><span className="eyebrow-new">MEASURABLE DEFENSE</span><h2>Threat intelligence<br /><em>at global scale.</em></h2></motion.div><div className="impact-grid"><Counter value="95%" label="threat detection accuracy" /><Counter value="12M+" label="URLs analyzed" /><Counter value="150K+" label="threats blocked" /><Counter value="40+" label="countries protected" /></div></div></section>
    <section className="testimonial-section"><div className="wrap"><span className="eyebrow-new">WHAT SECURITY LEADERS SAY</span><div className="testimonials">{[["PhishLense gave our analysts immediate context. We reduced phishing escalations by 83% in the first quarter.","Maya Chen","Security Lead, FinTech"],["The explainable verdicts finally made it simple to align incident response and leadership around the same decision.","Daniel Ortiz","CISO, Meridian Health"],["It feels designed for a modern SOC: fast, precise, and straightforward to integrate into the tools we already use.","Avery Patel","SOC Manager, Vector Cloud"]].map(([quote,name,role])=><motion.article {...reveal} whileHover={{y:-6}} key={name}><span>“</span><p>{quote}</p><b>{name}</b><small>{role}</small></motion.article>)}</div></div></section>
    <section className="pricing-section" id="pricing"><div className="wrap"><motion.div {...reveal} className="section-heading centered"><span className="eyebrow-new">PRICING THAT SCALES</span><h2>Start small. Defend<br /><em>without limits.</em></h2></motion.div><div className="price-grid">{plans.map(([name,sub,price,note,items],i)=><motion.article {...reveal} transition={{delay:i*.08}} className={`price-card ${i===1?"featured":""}`} key={name}>{i===1&&<><span className="popular">MOST POPULAR</span><span className="savings">SAVE 20% ANNUALLY</span></>}<h3>{name}</h3><p>{sub}</p><strong>{price === "Custom" ? price : <><small>$</small>{price}<i>/mo</i></>}</strong><em>{note}</em>{i===1&&<small className="social-proof">Used by 3,000+ security teams</small>}<a className={i===1?"primary-btn":"price-button"} href="#analyze">{i===2?"Talk to sales":"Get started"} <FiArrowRight /></a><ul>{items.map(x=><li key={x}><FiCheck /> {x}</li>)}</ul></motion.article>)}</div></div></section>

    <section className="faq-section" id="resources"><div className="wrap faq-grid"><motion.div {...reveal}><span className="eyebrow-new">FREQUENTLY ASKED</span><h2>Questions, answered<br /><em>with clarity.</em></h2><p>Need more detail? Our security team is here to help.</p><a className="text-button" href="mailto:security@phishlense.ai">Contact security <FiArrowRight /></a></motion.div><div className="faq-list">{faqs.map(([q,a],i)=><motion.div {...reveal} className={`faq-item ${openFaq===i?"active":""}`} key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} aria-expanded={openFaq===i}>{q}<FiChevronDown /></button>{openFaq===i&&<motion.p initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}}>{a}</motion.p>}</motion.div>)}</div></div></section>

    <section className="final-cta"><div className="wrap"><span className="badge"><b /> READY WHEN YOU ARE</span><h2>Start detecting threats before<br /><em>they become incidents.</em></h2><p>Give your security team the clarity to act with confidence.</p><div><a className="primary-btn" href="#analyze">Start free <FiArrowRight /></a><a className="secondary-btn" href="mailto:security@phishlense.ai">Book demo</a></div></div></section>
    <footer className="new-footer"><div className="wrap footer-grid"><div><a className="new-brand" href="#home"><i><FiShield /></i>PHISHLENSE</a><p>Protecting organizations from evolving phishing threats through AI-powered intelligence.</p><div className="socials"><FiLinkedin /><FiGithub /><FiGlobe /><FiActivity /></div></div>{[["Product","Platform","Intelligence","API","Pricing"],["Company","About","Security","Careers","Contact"],["Resources","Documentation","Status","Blog","Trust center"],["Legal","Privacy","Terms","Cookies","Responsible disclosure"]].map(([head,...links])=><div key={head}><b>{head}</b>{links.map(x=><a href="#home" key={x}>{x}</a>)}</div>)}</div><div className="wrap footer-bottom"><span>Copyright 2026 PhishLense. All rights reserved.</span><span>AI-powered intelligence for a safer internet.</span></div></footer>
  </main>;
}
export default App;
